theme = "congo"
baseURL = "https://ouspg.org/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0
# Update last modification date automatically
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
